use regex::Regex;
use serde_json::Value;
use std::sync::LazyLock;

use super::{Block, Decision};

struct Rule {
    pattern: Regex,
    message: &'static str,
    decision: Decision,
}

static RULES: LazyLock<Vec<Rule>> = LazyLock::new(|| {
    vec![
        // --- Generated files (ask — occasionally there's a legit reason) ---
        Rule {
            pattern: Regex::new(r"api\.gen\.go$").unwrap(),
            message: "api.gen.go is generated by oapi-codegen. Edit the OpenAPI spec in services/api-spec/ and run 'go generate' instead — confirm only if hand-editing is truly intended.",
            decision: Decision::Ask,
        },
        Rule {
            pattern: Regex::new(r"/Generated/.*\.(cs|java)$").unwrap(),
            message: "this is a generated protocol file. Edit the source definition and regenerate instead — confirm only if hand-editing is truly intended.",
            decision: Decision::Ask,
        },
        // --- Sensitive config (hard deny) ---
        Rule {
            pattern: Regex::new(r"\.claude/(settings\.json|hooks/)").unwrap(),
            message: "BLOCKED: modifying Claude config/hooks from an agent is not allowed. Ask the user to edit it manually.",
            decision: Decision::Deny,
        },
        // --- Guard tampering (hard deny) ---
        Rule {
            pattern: Regex::new(r"\.guard-state\.json$").unwrap(),
            message: "BLOCKED: only the user can modify guard state. Ask them to run 'guardctl on/off' manually.",
            decision: Decision::Deny,
        },
        // --- Secrets and credentials (hard deny) ---
        Rule {
            pattern: Regex::new(r"(?i)\.(env|pem|key|p12|pfx|jks|keystore)$").unwrap(),
            message: "BLOCKED: writing to a file that likely contains secrets or cryptographic material.",
            decision: Decision::Deny,
        },
        Rule {
            pattern: Regex::new(r"(?i)/(credentials|secrets?\.ya?ml|secrets?\.json|\.secret)$").unwrap(),
            message: "BLOCKED: writing to a file that likely contains secrets.",
            decision: Decision::Deny,
        },
        // --- Terraform state (ask — tf state surgery is sometimes needed) ---
        Rule {
            pattern: Regex::new(r"\.tfstate(\.backup)?$").unwrap(),
            message: "never hand-edit Terraform state files. Use 'terraform state' commands — confirm only if truly needed.",
            decision: Decision::Ask,
        },
        // --- Lock files (ask — sometimes a surgical fix is the right call) ---
        Rule {
            pattern: Regex::new(r"(package-lock\.json|yarn\.lock|go\.sum|packages\.lock\.json)$").unwrap(),
            message: "lock files should be updated by their package manager, not edited directly. Confirm only if intentional.",
            decision: Decision::Ask,
        },
    ]
});

pub fn check(input: &Value) -> Option<Block> {
    let file_path = input
        .pointer("/tool_input/file_path")
        .and_then(|v| v.as_str())?;

    for rule in RULES.iter() {
        if rule.pattern.is_match(file_path) {
            return Some(Block {
                decision: rule.decision,
                reason: rule.message.to_string(),
            });
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn input(path: &str) -> Value {
        json!({"tool_input": {"file_path": path}})
    }

    fn blocked(path: &str) -> bool {
        check(&input(path)).is_some()
    }

    fn decision_for(path: &str) -> Option<Decision> {
        check(&input(path)).map(|b| b.decision)
    }

    #[test]
    fn blocks_generated_go() {
        assert!(blocked("/Users/julia/Code/services/account/account_external/api.gen.go"));
    }

    #[test]
    fn allows_normal_go() {
        assert!(!blocked("/Users/julia/Code/services/account/account_impl/service.go"));
    }

    #[test]
    fn blocks_generated_protocol() {
        assert!(blocked("/Users/julia/Code/hytale/Protocol/Generated/Packets.cs"));
        assert!(blocked("/Users/julia/Code/hytale/Server/Generated/Handler.java"));
    }

    #[test]
    fn blocks_claude_config() {
        assert!(blocked("/Users/julia/.claude/settings.json"));
        assert!(blocked("/Users/julia/.claude/hooks/rtk-rewrite.sh"));
    }

    #[test]
    fn blocks_secrets() {
        assert!(blocked("/app/.env"));
        assert!(blocked("/app/server.pem"));
        assert!(blocked("/app/tls.key"));
        assert!(blocked("/app/secrets.json"));
        assert!(blocked("/app/secrets.yaml"));
    }

    #[test]
    fn blocks_tfstate() {
        assert!(blocked("/infra/terraform.tfstate"));
        assert!(blocked("/infra/terraform.tfstate.backup"));
    }

    #[test]
    fn blocks_lock_files() {
        assert!(blocked("/app/go.sum"));
        assert!(blocked("/app/package-lock.json"));
        assert!(blocked("/app/yarn.lock"));
    }

    #[test]
    fn blocks_guard_state_file() {
        assert!(blocked("/Users/julia/.claude/hooks/.guard-state.json"));
    }

    #[test]
    fn allows_normal_files() {
        assert!(!blocked("/app/src/main.rs"));
        assert!(!blocked("/app/service.go"));
        assert!(!blocked("/app/Program.cs"));
        assert!(!blocked("/app/README.md"));
    }

    // --- Decision classification ---

    #[test]
    fn secrets_are_deny() {
        assert_eq!(decision_for("/app/.env"), Some(Decision::Deny));
        assert_eq!(decision_for("/app/server.pem"), Some(Decision::Deny));
        assert_eq!(decision_for("/app/secrets.json"), Some(Decision::Deny));
    }

    #[test]
    fn claude_config_is_deny() {
        assert_eq!(
            decision_for("/Users/julia/.claude/settings.json"),
            Some(Decision::Deny)
        );
        assert_eq!(
            decision_for("/Users/julia/.claude/hooks/.guard-state.json"),
            Some(Decision::Deny)
        );
    }

    #[test]
    fn generated_files_are_ask() {
        assert_eq!(
            decision_for("/app/services/account/api.gen.go"),
            Some(Decision::Ask)
        );
        assert_eq!(
            decision_for("/app/Protocol/Generated/Packets.cs"),
            Some(Decision::Ask)
        );
    }

    #[test]
    fn tfstate_and_lockfiles_are_ask() {
        assert_eq!(decision_for("/infra/terraform.tfstate"), Some(Decision::Ask));
        assert_eq!(decision_for("/app/package-lock.json"), Some(Decision::Ask));
    }
}
