use regex::Regex;
use serde_json::Value;
use std::sync::LazyLock;

struct Rule {
    pattern: Regex,
    message: &'static str,
}

static RULES: LazyLock<Vec<Rule>> = LazyLock::new(|| {
    vec![
        // --- Generated files (DO NOT EDIT) ---
        Rule {
            pattern: Regex::new(r"api\.gen\.go$").unwrap(),
            message: "BLOCKED: api.gen.go is generated by oapi-codegen. Edit the OpenAPI spec in services/api-spec/ and run 'go generate' instead.",
        },
        Rule {
            pattern: Regex::new(r"/Generated/.*\.(cs|java)$").unwrap(),
            message: "BLOCKED: this is a generated protocol file. Edit the source definition and regenerate instead.",
        },
        // --- Sensitive config ---
        Rule {
            pattern: Regex::new(r"\.claude/(settings\.json|hooks/)").unwrap(),
            message: "BLOCKED: modifying Claude config/hooks requires manual confirmation.",
        },
        // --- Guard tampering ---
        Rule {
            pattern: Regex::new(r"\.guard-state\.json$").unwrap(),
            message: "BLOCKED: only the user can modify guard state. Ask them to run 'guardctl on/off' manually.",
        },
        // --- Secrets and credentials ---
        Rule {
            pattern: Regex::new(r"(?i)\.(env|pem|key|p12|pfx|jks|keystore)$").unwrap(),
            message: "BLOCKED: writing to a file that likely contains secrets or cryptographic material.",
        },
        Rule {
            pattern: Regex::new(r"(?i)/(credentials|secrets?\.ya?ml|secrets?\.json|\.secret)$").unwrap(),
            message: "BLOCKED: writing to a file that likely contains secrets.",
        },
        // --- Terraform state ---
        Rule {
            pattern: Regex::new(r"\.tfstate(\.backup)?$").unwrap(),
            message: "BLOCKED: never hand-edit Terraform state files. Use 'terraform state' commands.",
        },
        // --- Lock files ---
        Rule {
            pattern: Regex::new(r"(package-lock\.json|yarn\.lock|go\.sum|packages\.lock\.json)$").unwrap(),
            message: "BLOCKED: lock files should be updated by their package manager, not edited directly.",
        },
    ]
});

pub fn check(input: &Value) -> Option<String> {
    let file_path = input
        .pointer("/tool_input/file_path")
        .and_then(|v| v.as_str())?;

    for rule in RULES.iter() {
        if rule.pattern.is_match(file_path) {
            return Some(rule.message.to_string());
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn input(path: &str) -> Value {
        json!({"tool_input": {"file_path": path}})
    }

    fn blocked(path: &str) -> bool {
        check(&input(path)).is_some()
    }

    #[test]
    fn blocks_generated_go() {
        assert!(blocked("/Users/julia/Code/services/account/account_external/api.gen.go"));
    }

    #[test]
    fn allows_normal_go() {
        assert!(!blocked("/Users/julia/Code/services/account/account_impl/service.go"));
    }

    #[test]
    fn blocks_generated_protocol() {
        assert!(blocked("/Users/julia/Code/hytale/Protocol/Generated/Packets.cs"));
        assert!(blocked("/Users/julia/Code/hytale/Server/Generated/Handler.java"));
    }

    #[test]
    fn blocks_claude_config() {
        assert!(blocked("/Users/julia/.claude/settings.json"));
        assert!(blocked("/Users/julia/.claude/hooks/rtk-rewrite.sh"));
    }

    #[test]
    fn blocks_secrets() {
        assert!(blocked("/app/.env"));
        assert!(blocked("/app/server.pem"));
        assert!(blocked("/app/tls.key"));
        assert!(blocked("/app/secrets.json"));
        assert!(blocked("/app/secrets.yaml"));
    }

    #[test]
    fn blocks_tfstate() {
        assert!(blocked("/infra/terraform.tfstate"));
        assert!(blocked("/infra/terraform.tfstate.backup"));
    }

    #[test]
    fn blocks_lock_files() {
        assert!(blocked("/app/go.sum"));
        assert!(blocked("/app/package-lock.json"));
        assert!(blocked("/app/yarn.lock"));
    }

    #[test]
    fn blocks_guard_state_file() {
        assert!(blocked("/Users/julia/.claude/hooks/.guard-state.json"));
    }

    #[test]
    fn allows_normal_files() {
        assert!(!blocked("/app/src/main.rs"));
        assert!(!blocked("/app/service.go"));
        assert!(!blocked("/app/Program.cs"));
        assert!(!blocked("/app/README.md"));
    }
}
